import Vue from 'vue';

import DAvatar from './v-avatar/';
import DBadge from './v-badge/';
import DBreadcrumb from './v-breadcrumb';
import DButton from './v-button/';
import DButtonGroup from './v-button-group/';
import DCard, { DCardActions, DCardTitle, DCardSubtitle, DCardText } from './v-card';
import DCheckbox from './v-checkbox/';
import DChip from './v-chip/';
import DDetail from './v-detail';
import DDialog from './v-dialog';
import DDivider from './v-divider';
import DError from './v-error';
import DFancySelect from './v-fancy-select';
import DFieldTemplate from './v-field-template';
import DFieldSelect from './v-field-select';
import DForm from './v-form';
import DHover from './v-hover/';
import DIcon from './v-icon/';
import DInfo from './v-info/';
import DInput from './v-input/';
import DItemGroup, { DItem } from './v-item-group';
import DList, { DListGroup, DListItem, DListItemContent, DListItemHint, DListItemIcon } from './v-list/';
import DMenu from './v-menu/';
import DDrawer from './v-drawer/';
import DNotice from './v-notice/';
import DOverlay from './v-overlay/';
import DPagination from './v-pagination/';
import DProgressCircular from './v-progress/circular/';
import DProgressLinear from './v-progress/linear/';
import DRadio from './v-radio/';
import DSelect from './v-select/';
import DSheet from './v-sheet/';
import DSkeletonLoader from './v-skeleton-loader/';
import DSlider from './v-slider/';
import DSwitch from './v-switch/';
import DTable from './v-table/';
import DTabs, { DTab, DTabsItems, DTabItem } from './v-tabs/';
import DTextarea from './v-textarea';
import DTextOverflow from './v-text-overflow.vue';
import DUpload from './v-upload';

import VFlag from './v-flag';
Vue.component('v-flag', VFlag);
import VPlatform from './v-platform';
Vue.component('v-platform', VPlatform);

Vue.component('d-avatar', DAvatar);
Vue.component('d-badge', DBadge);
Vue.component('d-breadcrumb', DBreadcrumb);
Vue.component('d-button', DButton);
Vue.component('d-button-group', DButtonGroup);
Vue.component('d-card-actions', DCardActions);
Vue.component('d-card-subtitle', DCardSubtitle);
Vue.component('d-card-text', DCardText);
Vue.component('d-card-title', DCardTitle);
Vue.component('d-card', DCard);
Vue.component('d-checkbox', DCheckbox);
Vue.component('d-chip', DChip);
Vue.component('d-detail', DDetail);
Vue.component('d-dialog', DDialog);
Vue.component('d-divider', DDivider);
Vue.component('d-error', DError);
Vue.component('d-fancy-select', DFancySelect);
Vue.component('d-field-template', DFieldTemplate);
Vue.component('d-field-select', DFieldSelect);
Vue.component('d-form', DForm);
Vue.component('d-hover', DHover);
Vue.component('d-icon', DIcon);
Vue.component('d-info', DInfo);
Vue.component('d-input', DInput);
Vue.component('d-item-group', DItemGroup);
Vue.component('d-item', DItem);
Vue.component('d-list-group', DListGroup);
Vue.component('d-list-item-content', DListItemContent);
Vue.component('d-list-item-hint', DListItemHint);
Vue.component('d-list-item-icon', DListItemIcon);
Vue.component('d-list-item', DListItem);
Vue.component('d-list', DList);
Vue.component('d-menu', DMenu);
Vue.component('d-drawer', DDrawer);
Vue.component('d-notice', DNotice);
Vue.component('d-overlay', DOverlay);
Vue.component('d-pagination', DPagination);
Vue.component('d-progress-circular', DProgressCircular);
Vue.component('d-progress-linear', DProgressLinear);
Vue.component('d-radio', DRadio);
Vue.component('d-select', DSelect);
Vue.component('d-sheet', DSheet);
Vue.component('d-skeleton-loader', DSkeletonLoader);
Vue.component('d-slider', DSlider);
Vue.component('d-switch', DSwitch);
Vue.component('d-tab-item', DTabItem);
Vue.component('d-tab', DTab);
Vue.component('d-table', DTable);
Vue.component('d-tabs-items', DTabsItems);
Vue.component('d-tabs', DTabs);
Vue.component('d-textarea', DTextarea);
Vue.component('d-text-overflow', DTextOverflow);
Vue.component('d-upload', DUpload);

import TransitionBounce from './transition/bounce';
import TransitionDialog from './transition/dialog';
import TransitionExpand from './transition/expand';

Vue.component('transition-bounce', TransitionBounce);
Vue.component('transition-dialog', TransitionDialog);
Vue.component('transition-expand', TransitionExpand);

import RenderDisplay from '@/views/private/components/render-display';
import RenderTemplate from '@/views/private/components/render-template';
import SidebarDetail from '@/views/private/components/sidebar-detail/';
import FilterSidebarDetail from '@/views/private/components/filter-sidebar-detail';
import UserPopover from '@/views/private/components/user-popover';
import ValueNull from '@/views/private/components/value-null';

Vue.component('render-display', RenderDisplay);
Vue.component('render-template', RenderTemplate);
Vue.component('filter-sidebar-detail', FilterSidebarDetail);
Vue.component('sidebar-detail', SidebarDetail);
Vue.component('user-popover', UserPopover);
Vue.component('value-null', ValueNull);
